name: Django CI

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

jobs:
  build:

    runs-on: windows-latest
    strategy:
      max-parallel: 4
      matrix:
        python-version: [3.6]

    steps:
    - uses: actions/checkout@v2
    - name: Set up Python ${{ matrix.python-version }}
      uses: actions/setup-python@v1
      with:
        python-version: ${{ matrix.python-version }}
    - name: Install Dependencies
      run: |
        python -m pip install --upgrade pip
    - name: Run Tests
      run: |
        pip install wordcloud
        pip install fileupload
        pip install ipywidgets
        jupyter nbextension install --py --user fileupload
        jupyter nbextension enable --py fileupload
        pip install speechRecognition
        pip install PyAudio
        pip install portaudio
    - name: Test with pytest
      run: pytest WORDCLOUD.py --doctest-modules --junitxml=junit/test-results-${{ matrix.python-version }}.xml
    - name: Upload pytest test results
      uses: actions/upload-artifact@v2
      with:
          name: pytest-results-${{ matrix.python-version }}
          path: junit/test-results-${{ matrix.python-version }}.xml
        # Use always() to always run this step to publish test results when there are test failures
          if: ${{ always() }}
        
      
